---
title: Biostatistics Practice Problems
author: "J. Stephen Gosnell"
---

<!-- COMMENT NOT SHOW IN ANY OUTPUT: Code chunk below sets overall defaults for .qmd file; these inlcude showing output by default and looking for files relative to .Rpoj file, not .qmd file, which makes putting filesin different folders easier  -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

These problems are part of a book that is meant to accompany biostatistics courses I teach at Baruch College and the CUNY Graduate Center, but it may offer another perspective to anyone trying to learn statistics, R, or some combination. The course material now includes a

course notes/book

a website housing slides and associated material

-   this was the original "home" for the material, and it is being
    updated to point
    [here](https://jsgosnell.github.io/cuny_biostats_website/){target="_blank"}

tutorials for many lessons using Swirl

these practice problems (which exist for ease in rendering - read below)

How do make sure you understand this stuff?

Using these skills and applying concepts correctly to interpret data sets may seem easy when you read about them or listen during class, but practice is key to ensuring you understand the material. Practice problems are provided for each lesson in the course book. You can make a copy (technically a fork, since you can’t directly edit it) of the entire website in github @ https://github.com/jsgosnell/cuny_biostats_book and work from there. The benefit is this allows you to see updates to the site (if you sync your fork). The downside is you have to work interactively or build the entire site when you render a changed file. This is doable but may take more time than students need. Alternatively, you can download just the practice problems here. Your instructor may also provide alternative problems or use a different delivery method (like github classroom).

Solutions are also provided for all problems via the course notes, but try them before you look at the answers!